config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :units
  resources :ladders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ladder.rb
class Ladder < ApplicationRecord
    has_many :units
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :ladder
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game/game_controller.rb
module Game
    class GameController
        def initialize()
            unit = Unit.new()
            unit = roll_order(unit)
            puts unit[:roll]
        end

        def get_random_number(max, min = 1, round = true)
            return Game::Utilities.get_random_number(max, min, round)
        end

        def generate_unit

        end

        def generate_ladder
        end

        def generate_units
        end

        def generate_ladders
        end

        def do_turn(unit, order, last_turn)
            hit = roll_to_hit(unit)
            idx = order.find_index(unit)
            unit2 = idx == 0 ? order[1] : order[0]
            attackDiff = get_random_number(unit[:attack]) - get_random_number(unit2[:defense])
            dmg = 0

            if attackDiff > 0
                dmg = attackDiff
            else
                dmg = 1
            end

            puts "#{unit[:name]} strikes at #{unit2[:name]}!"

            if hit > get_random_number(unit2[:agility])
                puts "the attack hits #{unit2[:name]} (#{unit2[:hp]}) for #{dmg} damage!"
            elsif hit > unit2[:agility] * 2
                dmg = unit[:attack]
                puts "the attack hits #{unit2[:name]} (#{unit2[:hp]}) HARD for #{dmg} damage!"
            else
                dmg = 0
                puts "#{unit2[:name]} dodges the attack!"
            end

            check_damage_result = check_damage(unit2, dmg)
            fight_end = false

            if check_damage_result[:unit][:status] == 0
                puts "#{unit2[:name]} has perished!"
                fight_end = true
            end

            if last_turn == true
                fight_end = true
            end
            
            if fight_end == true
                puts "The match is over!"
            end

            update_units(unit, unit2)

            return {:end => fight_end}
        end

        def update_units(unit1, unit2)
        end

        def roll_order(unit)
            unit[:roll] = get_random_number(100)
            return unit
        end

        def roll_to_hit(unit)
            return get_random_number(unit[:agility], 1)
        end

        def check_damage(unit, dmg)
            health = unit.HP
            health -= dmg
            if health <= 0
                unit.Status = 0
                unit.HP = 0
            else
                unit.Status = 2
                unit.HP = health
            end
            return {:unit => unit}
        end

        def calculate_ladder_prize_value(units)
            val = 0
            i = 0
            while i < units.size do
                unit = units[i]
                val += (unit[:hp] + unit[:attack] + unit[:defense] + unit[:agility])
                i += 1
            end
            return val
        end
    end

    class Utilities
        def self.get_random_number(max, min = 1, round = true)
            num = 0;
            if round == true
                num = rand(min..max)
                num = num.floor
            else
                num = rand(min..max)
            end
            return num
        end
    end

    class Settings
        @@default_max_ladder_size = 10
        @@default_max_hp = 100
        @@default_max_attack = 100
        @@default_max_defense = 25
        @@default_max_agility = 125
        @@default_max_hit = 5
        @@max_turns = 10
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    game = Game::GameController.new()
  end
end

app/controllers/ladders_controller.rb
class LaddersController < ApplicationController
  before_action :set_ladder, only: [:show, :edit, :update, :destroy]

  # GET /ladders
  # GET /ladders.json
  def index
    @ladders = Ladder.all
  end

  # GET /ladders/1
  # GET /ladders/1.json
  def show
  end

  # GET /ladders/new
  def new
    @ladder = Ladder.new
  end

  # GET /ladders/1/edit
  def edit
  end

  # POST /ladders
  # POST /ladders.json
  def create
    @ladder = Ladder.new(ladder_params)

    respond_to do |format|
      if @ladder.save
        format.html { redirect_to @ladder, notice: 'Ladder was successfully created.' }
        format.json { render :show, status: :created, location: @ladder }
      else
        format.html { render :new }
        format.json { render json: @ladder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ladders/1
  # PATCH/PUT /ladders/1.json
  def update
    respond_to do |format|
      if @ladder.update(ladder_params)
        format.html { redirect_to @ladder, notice: 'Ladder was successfully updated.' }
        format.json { render :show, status: :ok, location: @ladder }
      else
        format.html { render :edit }
        format.json { render json: @ladder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ladders/1
  # DELETE /ladders/1.json
  def destroy
    @ladder.destroy
    respond_to do |format|
      format.html { redirect_to ladders_url, notice: 'Ladder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ladder
      @ladder = Ladder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ladder_params
      params.require(:ladder).permit(:name, :size, :description)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_params
      params.require(:unit).permit(:name, :hp, :attack, :defense, :agility, :xp, :points, :avatar, :ladder_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def get_random_number(max, min = 1, round = true)
        num = 0;
        if round == true
            num = floor(rand(min..max))
        else
            num = rand(min..max)
        end
        return num
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ladders_helper.rb
module LaddersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/ladders/_form.html.erb
<%= form_with(model: ladder, local: true) do |form| %>
  <% if ladder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ladder.errors.count, "error") %> prohibited this ladder from being saved:</h2>

      <ul>
        <% ladder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ladders/edit.html.erb
<h1>Editing Ladder</h1>

<%= render 'form', ladder: @ladder %>

<%= link_to 'Show', @ladder %> |
<%= link_to 'Back', ladders_path %>

app/views/ladders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ladders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ladders.each do |ladder| %>
      <tr>
        <td><%= ladder.name %></td>
        <td><%= ladder.size %></td>
        <td><%= ladder.description %></td>
        <td><%= link_to 'Show', ladder %></td>
        <td><%= link_to 'Edit', edit_ladder_path(ladder) %></td>
        <td><%= link_to 'Destroy', ladder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ladder', new_ladder_path %>

app/views/ladders/new.html.erb
<h1>New Ladder</h1>

<%= render 'form', ladder: @ladder %>

<%= link_to 'Back', ladders_path %>

app/views/ladders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ladder.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @ladder.size %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ladder.description %>
</p>

<%= link_to 'Edit', edit_ladder_path(@ladder) %> |
<%= link_to 'Back', ladders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gladdy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/units/_form.html.erb
<%= form_with(model: unit, local: true) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
        <% unit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hp %>
    <%= form.text_field :hp %>
  </div>

  <div class="field">
    <%= form.label :attack %>
    <%= form.text_field :attack %>
  </div>

  <div class="field">
    <%= form.label :defense %>
    <%= form.text_field :defense %>
  </div>

  <div class="field">
    <%= form.label :agility %>
    <%= form.text_field :agility %>
  </div>

  <div class="field">
    <%= form.label :xp %>
    <%= form.text_field :xp %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.text_field :avatar %>
  </div>

  <div class="field">
    <%= form.label :ladder_id %>
    <%= form.text_field :ladder_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hp</th>
      <th>Attack</th>
      <th>Defense</th>
      <th>Agility</th>
      <th>Xp</th>
      <th>Points</th>
      <th>Avatar</th>
      <th>Ladder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.hp %></td>
        <td><%= unit.attack %></td>
        <td><%= unit.defense %></td>
        <td><%= unit.agility %></td>
        <td><%= unit.xp %></td>
        <td><%= unit.points %></td>
        <td><%= unit.avatar %></td>
        <td><%= unit.ladder_id %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @unit.hp %>
</p>

<p>
  <strong>Attack:</strong>
  <%= @unit.attack %>
</p>

<p>
  <strong>Defense:</strong>
  <%= @unit.defense %>
</p>

<p>
  <strong>Agility:</strong>
  <%= @unit.agility %>
</p>

<p>
  <strong>Xp:</strong>
  <%= @unit.xp %>
</p>

<p>
  <strong>Points:</strong>
  <%= @unit.points %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @unit.avatar %>
</p>

<p>
  <strong>Ladder:</strong>
  <%= @unit.ladder_id %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>